'use client'

import { FileText, Image } from 'lucide-react'

export type DocPreviewProps = {
  /** Signed storage URL, generated by the consuming application. */
  mimeType: string | null
  name: string
  url: string | null
}

export function DocPreview({ url, mimeType, name }: DocPreviewProps) {
  if (!url) return <Fallback mimeType={mimeType} reason="no-url" />

  if (mimeType === 'application/pdf' || mimeType === 'text/plain' || mimeType === 'text/csv') {
    return (
      <iframe
        src={url}
        title={name}
        className="w-full rounded-sm border-0"
        style={{ height: '75vh', minHeight: 400 }}
      />
    )
  }

  if (mimeType?.startsWith('image/')) {
    return (
      <div className="bg-muted/30 flex justify-center rounded-sm p-6">
        {/* biome-ignore lint/performance/noImgElement: preview URLs are supplied by consuming applications. */}
        <img src={url} alt={name} className="max-h-[75vh] max-w-full rounded object-contain" />
      </div>
    )
  }

  return <Fallback mimeType={mimeType} reason="unsupported" />
}

function Fallback({
  mimeType,
  reason,
}: {
  mimeType: string | null
  reason: 'no-url' | 'unsupported'
}) {
  const Icon = mimeType?.startsWith('image/') ? Image : FileText
  const message =
    reason === 'no-url'
      ? 'No se pudo generar la URL de preview.'
      : 'Preview no disponible para este tipo de archivo.'

  return (
    <div className="text-muted-foreground flex flex-col items-center justify-center gap-2 py-14">
      <Icon className="size-9 opacity-30" />
      <p className="text-sm">{message}</p>
      {mimeType ? <p className="font-mono text-xs opacity-50">{mimeType}</p> : null}
      <p className="text-xs opacity-50">Usa el botón Descargar para abrir el archivo.</p>
    </div>
  )
}
