import { create } from "storybook/theming";

/** Shared manager and Docs theme using the approved Doscientos brand tokens. */
export const doscientosTheme = create({
  base: "light",
  fontCode: "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace",
  brandTitle: "doscientos UI",
  brandUrl: "https://doscientos.es",
  brandImage: "/doscientos-mark.svg",
  brandTarget: "_self",
  colorPrimary: "#2a4227",
  colorSecondary: "#355f31",
  appBg: "#edf1ec",
  appContentBg: "#fbfcfb",
  appPreviewBg: "#edf1ec",
  appBorderColor: "#dfe5dc",
  appBorderRadius: 12,
  textColor: "#182018",
  textInverseColor: "#ffffff",
  textMutedColor: "#687268",
  barTextColor: "#596359",
  barHoverColor: "#355f31",
  barSelectedColor: "#2a4227",
  barBg: "#fbfcfb",
  buttonBg: "#ffffff",
  buttonBorder: "#dfe5dc",
  booleanBg: "#e7ece5",
  booleanSelectedBg: "#355f31",
  inputBg: "#ffffff",
  inputBorder: "#dfe5dc",
  inputTextColor: "#182018",
  inputBorderRadius: 10,
});
